name: reprohealth_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  avatar_stack: ^1.2.0
  date_picker_timeline: ^1.2.5
  device_preview: ^1.1.0
  dio: ^5.3.4
  dotted_border: ^2.1.0
  dropdown_model_list: ^1.1.6
  email_otp: ^2.1.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  intl: ^0.18.1
  provider: ^6.1.1
  animated_snack_bar: ^0.4.0
  file_picker: ^6.1.1
  open_file: ^3.3.2
  rxdart: ^0.27.7
  just_the_tooltip: ^0.0.12
  shared_preferences: ^2.2.2


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
# flutter_assets:
#   assets_path: assets/
#   output_path: lib/constant/
#   filename: assets_constants.dart
